# Generated by Django 4.0.1 on 2024-10-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='profile_images', verbose_name='Picture')),
                ('description', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('study_group', models.CharField(choices=[('Science', 'Science'), ('Business Studies', 'Business Studies'), ('Humanities', 'Humanities')], max_length=50)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
    ]
